name: multipass
title: Multipass
icon: snap/gui/multipass-gui.svg
summary: Instant Ubuntu VMs
description: |
  Multipass is a tool to launch and manage VMs on Windows, Mac and Linux that
  simulates a cloud environment with support for cloud-init. Get Ubuntu
  on-demand with clean integration to your IDE and version control on your
  native platform.
license: GPL-3.0

adopt-info: multipass
confinement: classic
base: core18

architectures:
- build-on: amd64
  run-on: amd64
- build-on: armhf
  run-on: armhf
- build-on: arm64
  run-on: arm64

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: &library-path
        $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      PATH: &path
        $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
      XDG_CONFIG_HOME: &daemon-config $SNAP_DATA/config
      DAEMON_CONFIG_HOME: *daemon-config # temporary
    daemon: simple
  multipass:
    environment:
      <<: &client-environment
        LD_LIBRARY_PATH: *library-path
        PATH: *path
        QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
        XDG_DATA_HOME: $SNAP_USER_DATA/data
        XDG_CACHE_HOME: $SNAP_USER_DATA/cache
        XDG_CONFIG_HOME: $SNAP_USER_DATA/config
      DAEMON_CONFIG_HOME: *daemon-config # temporary
    command: bin/multipass
    completer: etc/bash_completion.d/snap.multipass
  gui:
    environment: *client-environment
    command: bin/multipass.gui
    autostart: multipass.gui.conditional-autostart.desktop

parts:
  multipass:
    plugin: cmake
    build-packages:
    - on arm64: [libgles2-mesa-dev]
    - on armhf: [libgles2-mesa-dev]
    - build-essential
    - cmake-extras
    - git
    - golang
    - libsystemd-dev
    - libvirt-dev
    - pkg-config
    - qtbase5-dev
    - qtbase5-dev-tools
    stage-packages:
    - on amd64: [libgl1]
    - on armhf: [libgles2-mesa]
    - on arm64: [libgles2-mesa]
    - libpng16-16
    - libqt5core5a
    - libqt5gui5
    - libqt5network5
    - libqt5widgets5
    - libxml2
    - libvirt0
    - dnsmasq
    source: .
    configflags:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    override-build: |
      snapcraftctl build
      set -e
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      VERSION=$( awk -F\" '/version_string/ { print $2 }' gen/multipass/version.h )
      snapcraftctl set-version ${VERSION}
      snapcraftctl set-grade $( echo ${VERSION} | grep -qe '^[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo stable || echo devel )

  qemu:
    plugin: nil
    override-pull: ""
    stage-packages:
    - on amd64: [qemu-system-x86]
    - on armhf: [qemu-system-arm]
    - on arm64: [qemu-system-arm]
    - qemu-utils
    - libslang2
    organize:
      usr/lib/*/pulseaudio/libpulsecommon-*.so: usr/lib/
      usr/share/seabios/bios-256k.bin: qemu/
      usr/share/seabios/vgabios-stdvga.bin: qemu/
      usr/share/seabios/kvmvapic.bin: qemu/
      usr/lib/ipxe/qemu/efi-virtio.rom: qemu/

  kvm-support:
    plugin: nil
    override-pull: ""
    stage-packages:
    - try: [msr-tools]

  network-utils:
    plugin: nil
    override-pull: ""
    stage-packages:
    - iproute2
    - iputils-ping
    - libatm1
    - libxtables12

  xterm:
    plugin: nil
    override-pull: ""
    stage-packages:
    - xterm
    stage:
    - -usr/lib/*/libfreetype.so.6
    - -usr/share/doc/libfreetype6/FTL.TXT.gz
    - -usr/share/doc/libfreetype6/TODO
    - -usr/share/doc/libfreetype6/changelog.Debian.gz
    - -usr/share/doc/libfreetype6/pcf/README

  glue:
    plugin: dump
    source: snap-wrappers
